function Initiate_Visuals_Simpler(nSeqMax,refState,transientLenThr, maxProbTol,insPenalty,segPenalty, minDistTol,axes_Handle,FileName,Undirected_Tag,Directed_Tag,Save_Tag)

if FileName ~=0
uiopen(FileName,1);
elseif FileName==0
    disp('No File Loaded')
end


% % % %for input into refState slider max 
% % % nStates=numstates(seq{:});

%must have all parameter variable available in this function

loc       = cell(1,1);
grouping  = cell(1,1);
links     = cell(1,1);
seqInfo   = cell(1,1);

[loc, grouping, links, seqInfo] =...
      clusterseq(seq,...
                 'nSeqMax',nSeqMax,...                                 
                 'refState',refState,...                                 
                 'transientLenThr',transientLenThr,...                     
                 'maxProbTol',maxProbTol ,...                               
                 'insPenalty',insPenalty,...                                 
                 'segPenalty',segPenalty,...                               
                 'minDistTol',minDistTol);
             
             
if Undirected_Tag==true && Directed_Tag == false
% Please note that the following is for the UNDIRECTED graph GUI.

graphOpts.undirected.visibility   = false;    % The figure generated should not be visible
graphOpts.undirected.handle       = true;     % The argout (fig) is the number of the figure that you want to copy into your GUI
graphOpts.directed.visibility     = false;
graphOpts.directed.handle         = false;

if Save_Tag==false
% displays graphic in gui
viewclusters3(axes_Handle,grouping,...
                   'minEdgeCrossings',true,...
                   'txt',cellstr(num2str(labels)),...
                   'graphOpts',graphOpts);
end % SaveTag==false

if Save_Tag==true
   %generates undirected graphic figure
   %prompts user to input filename for saving undirected figure as .fig file
   %figure is invisible to the user
   save_viewclusters_figure(grouping,...
                   'minEdgeCrossings',true,...
                   'txt',cellstr(num2str(labels)),...
                   'graphOpts',graphOpts);
   
   
   %prompts user to input filename for saving .mat file containing selected parameters of graphics figure
   save_parameters('nSeqMax',nSeqMax,...                                 
                 'refState',refState,...                                 
                 'transientLenThr',transientLenThr,...                     
                 'maxProbTol',maxProbTol ,...                               
                 'insPenalty',insPenalty,...                                 
                 'segPenalty',segPenalty,...                               
                 'minDistTol',minDistTol,...
                 'Undirected_Tag',Undirected_Tag,...
                 'Directed_Tag',Directed_Tag,...
                 'graphOpts',graphOpts);
                  
end % if SaveTag==true

elseif Undirected_Tag==false && Directed_Tag==true
 % Please note that the following is for the DIRECTED graph GUI.

graphOpts.undirected.visibility   = false;    % The figure generated should not be visible
graphOpts.undirected.handle       = false;     % The argout (fig) is the number of the figure that you want to copy into your GUI
graphOpts.directed.visibility     = false;
graphOpts.directed.handle         = true;

if Save_Tag==false
viewclusters3(axes_Handle,grouping,...
                   'minEdgeCrossings',true,...
                   'txt',cellstr(num2str(labels)),...
                   'graphOpts',graphOpts);
end % if SaveTag==false

if Save_Tag==true
   %generates directed graphic figure
   %prompts user to input filename for saving directed figure as .fig file
   %figure is invisible to the user
   save_viewclusters_figure(grouping,...
                   'minEdgeCrossings',true,...
                   'txt',cellstr(num2str(labels)),...
                   'graphOpts',graphOpts);
%    delete figures %delete invisible figure
   
   %prompts user to input filename for saving .mat file containing selected parameters of graphics figure
   save_parameters('nSeqMax',nSeqMax,...                                 
                 'refState',refState,...                                 
                 'transientLenThr',transientLenThr,...                     
                 'maxProbTol',maxProbTol ,...                               
                 'insPenalty',insPenalty,...                                 
                 'segPenalty',segPenalty,...                               
                 'minDistTol',minDistTol,...
                 'Undirected_Tag',Undirected_Tag,...
                 'Directed_Tag',Directed_Tag,...
                 'graphOpts',graphOpts);
   
   
end % if SaveTag==true
end %if Undirected_Tag==true && Directed_Tag == false
    