%%
load data_clusterseq

%%
disp('**********');
disp('... Clustering factor analyzer state sequences ...');
%
locTrain                = cell(nPatients,1);
locTest                 = cell(nPatients,1);
groupingTrain           = cell(nPatients,1);
groupingTest            = cell(nPatients,1);
linksTrain              = cell(nPatients,1);
linksTest               = cell(nPatients,1);
seqInfoTrain            = cell(nPatients,1);
seqInfoTest             = cell(nPatients,1);

% numStates USAGE
pa                      = 1;
m                       = 1;
nStates                 = numstates(seqTest{pa}{m});
disp(nStates)


minDistTol              = 7;
for pa=pa_select
  for m=1:nGroups
    % Train data
    [locTrain{pa}, groupingTrain{pa}, linksTrain{pa}, seqInfoTrain{pa}] =...
      clusterseq(sqTrain{pa}{m},...
                 'nSeqMax', Inf,...
                 'minDistTol', minDistTol);
  
    % Test data
    [locTest{pa}, groupingTest{pa}, linksTest{pa}, seqInfoTest{pa}] =...
      clusterseq(seqTest{pa}{m},...
                 'nSeqMax', Inf,...
                 'minDistTol', minDistTol);
  end % for m=1:nGroups
end % for pa=pa_select
%
disp('Complete');
disp('**********');
%%
disp('**********');
disp('... View clustered factor analyzer state sequences ...');
%
graphOpts.undirected.visibility   = true;
graphOpts.undirected.handle       = true;
graphOpts.directed.visibility     = false;
graphOpts.directed.handle         = true;

pa                          = 2;
fig = viewclusters(groupingTrain{pa},...
                   'minEdgeCrossings',true,...
                   'txt',cellstr(num2str(dataInfo{pa})),...
                   'graphOpts',graphOpts);
% viewclusters(groupingTrain{pa},'minEdgeCrossings',true,'txt',[]);


% updated viewclusters USAGE (in your code)
%
% Please note that the following is for the UNDIRECTED graph GUI. I think it's
% fairly straightforward to write the corresponding code for the DIRECTED
% graph GUI.
%
% graphOpts.undirected.visibility   = false;    % The figure generated should not be visible
% graphOpts.undirected.handle       = true;     % The argout (fig) is the number of the figure that you want to copy into your GUI
% graphOpts.directed.visibility     = false;
% graphOpts.directed.handle         = false;
% fig = viewclusters(groupingTrain{pa},...
%                    'minEdgeCrossings',true,...
%                    'txt',cellstr(num2str(dataInfo{pa})),...
%                    'graphOpts',graphOpts);

% h = findobj(fig,'type','axes');               % Get the handle of the plot in the figure generated by viewclusters
%                                               % (Please note that the figure is invisible.)
% s = copyobj(allchild(h), axesHandle);                   % Copy the plot to your GUI
% delete(fig)                                   % Delete the figure (even though it is invisible) after the copy
%
disp('Complete');
disp('**********');